# Generated by Django 5.1 on 2026-06-15 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('user_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=128)),
                ('address', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'account_user',
            },
        ),
        migrations.CreateModel(
            name='AdministratorAdmin',
            fields=[
                ('admin_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'administrator_admin',
            },
        ),
        migrations.CreateModel(
            name='ShoppingCategory',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'shopping_category',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItem',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('manufacturer', models.CharField(max_length=32)),
                ('color', models.CharField(max_length=16)),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('recommended', models.BooleanField(default=False)),
                ('category', models.ForeignKey(db_column='category_id', on_delete=django.db.models.deletion.CASCADE, to='app.shoppingcategory')),
            ],
            options={
                'db_table': 'shopping_item',
            },
        ),
        migrations.CreateModel(
            name='ShoppingItemsincart',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='app.shoppingitem')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.accountuser')),
            ],
            options={
                'db_table': 'shopping_itemsincart',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchase',
            fields=[
                ('purchase_id', models.IntegerField(primary_key=True, serialize=False)),
                ('destination', models.CharField(max_length=256)),
                ('booked_date', models.DateField(auto_now_add=True)),
                ('cancel', models.BooleanField(default=False)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, to='app.accountuser')),
            ],
            options={
                'db_table': 'shopping_purchase',
            },
        ),
        migrations.CreateModel(
            name='ShoppingPurchasedetail',
            fields=[
                ('purchase_detail_id', models.IntegerField(primary_key=True, serialize=False)),
                ('amount', models.IntegerField()),
                ('item', models.ForeignKey(db_column='item_id', on_delete=django.db.models.deletion.CASCADE, to='app.shoppingitem')),
                ('purchase', models.ForeignKey(db_column='purchase_id', on_delete=django.db.models.deletion.CASCADE, to='app.shoppingpurchase')),
            ],
            options={
                'db_table': 'shopping_purchasedetail',
            },
        ),
    ]
